import sys


def ictclas_to_pku(line):
    dic = {
        'n': 'n',
        'nr': 'nr',
        'nr1': 'nr',
        'nr2': 'nr',
        'nrj': 'nr',
        'nrf': 'nr',
        'ns': 'ns',
        'nsf': 'ns',
        'nt': 'nt',
        'nz': 'nz',
        'nl': 'l',
        'ng': 'Ng',
        'n_new': 'n',
        'njtgj': 'n',
        'ntbj': 'n',
        'ntsa': 'n',
        'ntzj': 'n',
        '词性': 'n',
        'nthub': 'n',
        'ntyr': 'n',
        'ntsd': 'n',
        'ntyn': 'n',
        'ntsh': 'n',
        'n_newword': 'n',
        'ntzy': 'n',
        'ntgm': 'n',
        'ntss': 'n',
        'ntxz': 'n',
        'nttj': 'n',
        'ntcq': 'n',
        'ntes': 'n',
        'ntuk': 'n',
        'ntsx': 'n',
        'ntme': 'n',
        'ntgx': 'n',
        'ntqc': 'n',
        'ntit': 'n',
        'News': 'nx',
        'ntsc': 'n',
        'ntqz': 'n',
        'nthun': 'n',
        'ntah': 'n',
        'ntcb': 'n',
        'ntrqg': 'n',
        'nthen': 'n',
        'nthan': 'n',
        'xe': 'nx',
        'ntdc': 'n',
        'dl': 'l',
        'ntgd': 'n',
        'ntjs': 'n',
        'ntjj': 'n',
        'nswyy': 'n',
        'nthk': 'n',
        '新增': 'n',
        'ntdb': 'n',
        'ntz': 'n',
        'nv': 'n',
        'ntan': 'n',
        'nthl': 'n',
        'ntgz': 'n',
        'ntau': 'n',
        'ntqg': 'n',
        '术': 'nx',
        'ntkr': 'n',
        'ntjx': 'n',
        'ntjd': 'n',
        'ntsz': 'n',
        'yxb': 'y',
        'ntkrn': 'n',
        'nttc': 'n',
        'ntjp': 'n',
        'Mg': 'm',
        'nms': 'n',
        'ntjk': 'n',
        'ntthk': 'n',
        'ntfj': 'n',
        'ntjl': 'n',
        'ntheb': 'n',
        'ntrs': 'n',
        'nttw': 'n',
        'ntcj': 'n',
        'ntus': 'n',
        'ntgs': 'n',
        'ntot': 'n',
        'ntcn': 'n',
        'nttqg': 'n',
        'ntln': 'n',
        'ntts': 'n',
        'dg': 'Dg',
        'yxz': 'y',
        'ntfr': 'n',
        't': 't',
        'tg': 'tg',
        's': 's',
        'f': 'f',
        'v': 'v',
        'vd': 'vd',
        'vn': 'vn',
        'vshi': 'v',
        'vyou': 'v',
        'vf': 'v',
        'vx': 'v',
        'vi': 'v',
        'vl': 'l',
        'vg': 'vg',
        'a': 'a',
        'ad': 'ad',
        'an': 'an',
        'ag': 'Ag',
        'al': 'l',
        'b': 'b',
        'bl': 'l',
        'z': 'z',
        'r': 'r',
        'rr': 'r',
        'rz': 'r',
        'rzt': 'r',
        'rzs': 'r',
        'rzv': 'r',
        'ry': 'r',
        'ryt': 'r',
        'rys': 'r',
        'ryv': 'r',
        'rg': 'r',
        'Rg': 'r',
        'R': 'r',
        'm': 'm',
        'mq': 'm',
        'q': 'q',
        'qv': 'q',
        'qt': 'q',
        'd': 'd',
        'p': 'p',
        'P': 'p',
        'pba': 'p',
        'pbei': 'p',
        'c': 'c',
        'cc': 'c',
        'u': 'u',
        'uzhe': 'u',
        'ule': 'u',
        'uguo': 'u',
        'ude1': 'u',
        'ude2': 'u',
        'ude3': 'u',
        'usuo': 'u',
        'udeng': 'u',
        'uyy': 'u',
        'udh': 'u',
        'uls': 'u',
        'uzhi': 'u',
        'ulian': 'u',
        'e': 'e',
        'y': 'y',
        'o': 'o',
        'h': 'h',
        'k': 'k',
        'x': 'nx',
        'xx': 'nx',
        'xu': 'nx',
        'w': 'w',
        'wkz': 'w',
        'wky': 'w',
        'wyz': 'w',
        'wyy': 'w',
        'wj': 'w',
        'ww': 'w',
        'wt': 'w',
        'wd': 'w',
        'wf': 'w',
        'wn': 'w',
        'wm': 'w',
        'ws': 'w',
        'wp': 'w',
        'wb': 'w',
        'wh': 'w',
    }
    if line[-1] == '\n':
        line = line[:-1]
    if line[-1] == ' ':
        line = line[:-1]
    words = line.split(" ")
    for w in range(len(words)):
        sep = words[w].split("/")
        print(sep[0])
        sep[1] = dic[sep[1]]
        words[w] = sep[0] + "/" + sep[1]
    # print(" ".join(words) + '\n')
    return(" ".join(words) + '\n')


if __name__ == '__main__':
    if len(sys.argv) != 2:
        print("please provide one txt filename")
    else:
        filename = sys.argv[1]
        ict_file = open("output_ict\\" + filename, 'r', encoding="utf-8-sig")
        pku_file = open("output_pku\\" + filename, 'w', encoding="utf-8-sig")
        for line in ict_file:
            g = pku_file.write(ictclas_to_pku(line))
        ict_file.close()
        pku_file.close()
